# Configuration to register with eureka server to implement the service discovery
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-register: true  
    register-with-eureka: true  
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka} 
